'use strict';
async function openMeteoLesen() {
    // let url = 'https://api.open-meteo.com/v1/forecast?latitude=48.2752&longitude=8.8546&daily=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,daylight_duration,sunshine_duration,uv_index_max,uv_index_clear_sky_max,rain_sum,showers_sum,snowfall_sum,precipitation_sum,precipitation_hours,precipitation_probability_max,et0_fao_evapotranspiration,shortwave_radiation_sum,wind_direction_10m_dominant,wind_gusts_10m_max,wind_speed_10m_max&hourly=temperature_2m,precipitation,precipitation_probability,rain,showers,snowfall,weather_code,surface_pressure,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,visibility,evapotranspiration,et0_fao_evapotranspiration,vapour_pressure_deficit,pressure_msl,relative_humidity_2m,dew_point_2m,apparent_temperature,snow_depth,wind_speed_10m,wind_direction_10m,wind_gusts_10m,is_day&timezone=Europe%2FBerlin&forecast_days=10';
    // let url = `https://api.open-meteo.com/v1/forecast?latitude=48.2752&longitude=8.8546&daily=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,daylight_duration,sunshine_duration,uv_index_max,uv_index_clear_sky_max,rain_sum,showers_sum,snowfall_sum,precipitation_sum,precipitation_hours,precipitation_probability_max,et0_fao_evapotranspiration,shortwave_radiation_sum,wind_direction_10m_dominant,wind_gusts_10m_max,wind_speed_10m_max&models=icon_seamless&hourly=temperature_2m,precipitation,precipitation_probability,rain,showers,snowfall,weather_code,surface_pressure,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,visibility,evapotranspiration,et0_fao_evapotranspiration,vapour_pressure_deficit,pressure_msl,relative_humidity_2m,dew_point_2m,apparent_temperature,snow_depth,wind_speed_10m,wind_direction_10m,wind_gusts_10m,is_day&timezone=Europe%2FBerlin&forecast_days=7`;
    let url = `https://api.open-meteo.com/v1/forecast?latitude=48.2752&longitude=8.8546&daily=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,sunrise,sunset,daylight_duration,sunshine_duration,uv_index_max,uv_index_clear_sky_max,rain_sum,showers_sum,snowfall_sum,precipitation_sum,precipitation_hours,precipitation_probability_max,et0_fao_evapotranspiration,shortwave_radiation_sum,wind_direction_10m_dominant,wind_gusts_10m_max,wind_speed_10m_max&models=icon_seamless&hourly=temperature_2m,sunshine_duration,precipitation,precipitation_probability,rain,showers,snowfall,weather_code,surface_pressure,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,visibility,evapotranspiration,et0_fao_evapotranspiration,vapour_pressure_deficit,pressure_msl,relative_humidity_2m,dew_point_2m,apparent_temperature,snow_depth,wind_speed_10m,wind_direction_10m,wind_gusts_10m,is_day&timezone=Europe%2FBerlin&forecast_days=7`;
    let response = await fetch(url);
    let commits = await response.json();
    wetterVerarbeiten(commits);
}

// https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m&models=icon_seamless&past_days=0&forecast_days=7